### ISSUE TITLE
Add community guidelines

### ISSUE THREAD

**Issue by Athanasiamo** [samhforbes/PupillometryR#11]
There is currently no information on:
1. how to contribute
2. how to make a bug report
3. how to seek support

Please add some simple instructions to the README or package DESCRIPTION this.

The DESCRIPTION for instance allows for a `BugReports:` field

**Comment by samhforbes** [comment]
Thanks for flagging this! The description currently has a BugReports field, but this will be made clearer in the new README file as well as the other two being made explicit.
