### ISSUE TITLE
possibility of implementing factorial experimental design in make_pupillometryr_data 

### ISSUE THREAD

**Issue by ufangYang** [samhforbes/PupillometryR#17]
Compared to the example in the paper, do you think it is possible to fit a 2 *3 *2  * 2 experimental design in the function of `make_pupillometryr_data`?

For example: 

make_pupillometryr_data(data = pupil_data,
                                 subject = ID,
                                 trial = Trial,
                                 time = Time,
                                 condition = Type1,
                                    other= c(Type2,Type3,Type4))

thanks!

**Comment by samhforbes** [comment]
Hi @ufangYang thanks for the suggestion.
I haven't played out such a scenario to date as certain analyses (for example the functional analysis) are predicated on having a simple 2 condition design. For the gams analysis it should be fine though, just be careful in how that is set up. IF trial is unique to any given design condition (ie not split into 2 parts or something) then the cleaning functions should also work just fine.
I hope that partly answers your question!

**Comment by samhforbes** [comment]
@ufangYang The latest dev version may go some way to making this easier, if you would like to give it a try.
