### ISSUE TITLE
using the regress function with NA data

### ISSUE THREAD

**Issue by christinasen** [samhforbes/PupillometryR#18]
Hi there, I'm following the PupillometryR tutorial, and am getting stuck at the regress function. I think it has to do with my data having blinks coded as NA, because when I filter out the NA rows, the regress function works. But I am wondering if there is a way to keep rows in which there is data in right eye but an NA in the left eye (or vice versa), rather than just removing all NAs. When I filter out all the NA's, I lose about 20% of my original data, so I'm hoping there is a way to work around this and still use the regress function.

This is the error message I receive:
> Error: Problem with `mutate()` column `pupil1newkk`.
i `pupil1newkk = .predict_right(DiameterPupilRightEye, DiameterPupilLeftEye)`.
x 0 (non-NA) cases
i The error occurred in group 1395: Subject = 17, StimNo = 60a, ExpCondition = bias, partofexperiment = "end".

Thank you in advance!

**Comment by samhforbes** [comment]
Hi @christinasen without seeing the data it looks like perhaps the regress function is not what you want to use, as it looks like there are trials where only one of those pupils are available. Were you collecting data from both eyes, or was the eye being used variable across participants (or both)? Is the plan to just fill in the gaps with the other eye, or to use both eyes to add a degree of smoothing? If you just want to make sure that your pupil column contains right eye, or left when there is no right, you can do that by making a new column in R.

**Comment by samhforbes** [comment]
You may also be able to check and see whether the issue is the same one as highlighted in #19

**Comment by christinasen** [comment]
Hi @samhforbes, thank you for the quick response! I was collecting data from both eyes, though it seems that there was randomly data missing from one of the eyes. 
Thank you for directing me to the issue in #19, I also used a Tobii eye-tracker. I decided on creating a new variable which is the average of the right and left eye diameters, and skipped the regress function.
