### ISSUE TITLE
Error in grouped_df_impl(data, unname(vars), drop) :    Column `<empty>` is unknown

### ISSUE THREAD

**Issue by bababen** [samhforbes/PupillometryR#2]
I just installed the PupillometryR package and am working through the tutorial on the readme.md and get stuck at the regressed_data step:

     regressed_data <- regress_data(data = new_data, pupil1 = RPupil, pupil2 = LPupil)

Error in grouped_df_impl(data, unname(vars), drop) : 
  Column `<empty>` is unknown

I am running R version 3.5.1 (2018-07-02)

**Comment by samhforbes** [comment]
Hi @bababen 
I suspect the issue is that a column type wasn't specified earlier. 
Do you have some data that makes a minimal reproducible example, so I can investigate the issue?
Thanks,
Sam

**Comment by bababen** [comment]
I'm using the "pupil_data" file from the tutorial on the readme.md page.  As far as I can tell, I've copied the code exactly as it is on the introduction page.  

Here are the column types before I try to run regress_data:

sapply(new_data, class)
         ID       Trial        Time      RPupil      LPupil     Timebin        Type 
"character"    "factor"   "numeric"   "numeric"   "numeric"   "numeric" "character"

**Comment by samhforbes** [comment]
Hi @bababen 
Did you run the preceding steps?

I find if I run all of the below from the README it should work:

> library(PupillometryR)

> data("pupil_data")
> 
> #Check that IDs are not numeric
> pupil_data$ID <- as.character(pupil_data$ID)
> #remove participant number 8, who had problematic data
> pupil_data <- subset(pupil_data, ID != 8)
> #blinks were registered as -1, so replace with NAs
> pupil_data$LPupil[pupil_data$LPupil == -1] <- NA
> pupil_data$RPupil[pupil_data$RPupil == -1] <- NA
> library(ggplot2)
> theme_set(theme_classic(base_size = 12))
> Sdata <- make_pupillometryr_data(data = pupil_data,
+                                  subject = ID,
+                                  trial = Trial,
+                                  time = Time,
+                                  condition = Type)
> new_data <- replace_missing_data(data = Sdata)

> regressed_data <- regress_data(data = new_data,
+                                pupil1 = RPupil,
+                                pupil2 = LPupil)


Another possibility is that you have an older version of either dplyr or PupillometryR. Could you try updating them and seeing if you run into the same issue?
Thanks,
Sam

**Comment by samhforbes** [comment]
Sorry - forgot that adding plusses at the beginning of a new line would make it look like that!

**Comment by bababen** [comment]
updating dplyr worked!
