### ISSUE TITLE
baseline by first n samples

### ISSUE THREAD

**Issue by hcuve** [samhforbes/PupillometryR#3]
hi @samhforbes really great work with the package!

I was wondering if, for baselining, it would be also useful to have a different way to specify the baseline period, in addition to the the start and stop to specify for instance the first 100 ms, there is also a way to specify the the first **n** samples as the baseline, (e.g. the first 20 samples). Is this already possible with this package? 

Thank you,
Helio

**Comment by samhforbes** [comment]
Hi @hcuve ,
Thanks for getting in touch - this is a good idea. If you know your sampling rate it should be possible to work backwards from there, I will look at whether this should be added in the next update, however.
Thanks,
Sam
